#application-prod.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gahyeonbot
    driver-class-name: org.postgresql.Driver
    username: gahyeonbot_app
    password: ${POSTGRES_PROD_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.gahyeonbot: INFO
    org.springframework.web: INFO



server:
  port: 8080

#  실행 파라미터로
# --spring.profiles.active=prod
# IntelliJ Run/Debug Configurations → VM Options에
# -Dspring.profiles.active=prod
