package com.gahyeonbot.services.ai.agent;

public enum AgentEventType {
    RUN_CREATED,
    RUN_STARTED,
    MODEL_CALL_STARTED,
    MODEL_CALL_COMPLETED,
    TOOL_CALL_REQUESTED,
    TOOL_CALL_STARTED,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_FAILED,
    APPROVAL_REQUESTED,
    APPROVAL_RESOLVED,
    BACKGROUND_WAIT_STARTED,
    BACKGROUND_RESULT_RECEIVED,
    RUN_SUCCEEDED,
    RUN_FAILED,
    RUN_CANCELLED
}
